Repository openshift/deadmanssnitch-operator, pull requests merged in 2019-04, with the labels that each got.

#4 fixed some error messages, crhanged syncset secret
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
Labels: size/S

#6 Update Dockerflie add build scripts and add Makefile
  Makefile
  build/Dockerfile
  config/templates/deadmanssnitch-operator-csv-template.yaml
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
  hack/app_sre_pr_check.sh
  hack/generate-operator-bundle.py
  hack/olm-registry/olm-artifacts-template.yaml
Labels: size/L

#8 removed the crd section in the generate-operator-bundle
  hack/generate-operator-bundle.py
Labels: size/XS

#9 SREP-1143: Prep for CI Pipeline
  Makefile
  OWNERS
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  config/config.go
  project.mk
  standard.mk
Labels: lgtm, size/L

#10 Remove -x option to bash in SHELL
  Makefile
Labels: approved, lgtm, priority/awaiting-more-evidence, size/XS

#12 Fix catalog subscription ref
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#14 attempt to setup the clusterRole
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/S

#15 only look at installed clusterdeployments
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
Labels: approved, lgtm, size/M

#16 fixed bug where syncset clusterdeploymentref was wrong
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
Labels: approved, lgtm, size/M

#17 changing syncset to 'sync' from upsert
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
Labels: approved, lgtm, size/XS

#18 made the snitchname be clustername + basedomain
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
Labels: approved, lgtm, size/XS
