Repository openshift/deadmanssnitch-operator, pull requests merged in 2019-06, with the labels that each got.

#27 changed dms to default of 15 minutes instead of daily
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
Labels: approved, lgtm, size/XS

#28 exiting the reconciler loop after adding the finalizer
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
Labels: approved, lgtm, size/S

#29 fixed a bug when searching for existing snitches. Now it will re-use a snitch if one already exists
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
Labels: approved, lgtm, size/XS

#30 Remove ServiceMonitor in favor of Route for external scraping
  cmd/manager/main.go
  deploy/role.yaml
  pkg/metrics/service.go
Labels: approved, lgtm, size/L
