Repository openshift/deadmanssnitch-operator, pull requests merged in 2019-10, with the labels that each got.

#40 Add support for a 'noalerts' label
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
Labels: approved, lgtm, size/M

#41 Remove SyncSet if noalerts label is added
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
Labels: approved, lgtm, size/L

#42 Allow opeator to delete syncset
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#43 Refactoring and additional tests
  config/config.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/L

#46 Updated OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#44 use pre-created secret instead of embed in syncset
  config/config.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller.go
  pkg/controller/deadmanssnitch/deadmanssnitch_controller_test.go
  pkg/utils/utils.go
Labels: approved, lgtm, size/L
