Repository openshift/deadmanssnitch-operator, pull requests merged in 2019-09, with the labels that each got.

#38 Update OWNERS add jharrington22 remove aweiteka
  OWNERS
Labels: approved, lgtm, size/XS

#37 Update to operator-custom-metrics v0.2.1
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/builder.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metrics.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/metricsconfig.go
  vendor/github.com/openshift/operator-custom-metrics/pkg/metrics/service.go
Labels: approved, lgtm, size/L

#36 add yaml validation
  hack/app_sre_pr_check.sh
  hack/validate_yaml.py
Labels: approved, lgtm, size/M
